In [ ]:
image_ids = [101, 102, 103, 104, 105]

dataset = {
    "name": "Microsoft vs Code", # 微软大战代码！
    "labels": ("microsoft", "code")
}

# （1）输出数据集名称
print(dataset["name"])

# （2）取出前三张图片编号
first_three = image_ids[:3]

# （3）输出最后一张图片编号
last_image = image_ids[-1]

# （4）新增键值对："num_images": 5000
dataset["name_images"]=5000
print(dataset)

Microsoft vs Code
{'name': 'Microsoft vs Code', 'labels': ('microsoft', 'code'), 'name_images': 5000}


In [ ]:
with open("data.txt", "r", encoding="utf-8") as f:
    content = f.read()
count = content.count("python")

print(count)

4


In [ ]:
import numpy as np
A = np.random.randint(1,101,size=(10,10))
print(A)

B = np.eye(10)
print(B)
C = A*B
print(C)

A[A>80]=0
print(A)

A = np.random.randint(1,101,size=(10,10))

s1 = A[:5, :5]
s2 = A[:5, 5:]
s3 = A[5:, :5]
s4 = A[5:, 5:]
mean1 = np.mean(s1)
mean2 = np.mean(s2)
mean3 = np.mean(s3)
mean4 = np.mean(s4)

print(mean1, mean2, mean3, mean4)

E = np.split(A,2,axis=0)
print(E)
F = []
for part in E:
    x =np.split(part,2,axis=1)
    F.append(x)
print(F)
x1 = F[0][0]
x2 = F[1][0]
x3 = F[0][1]
x4 = F[1][1]
print(x1.mean(),x2.mean(),x3.mean(),x4.mean())

[[ 34  24  34  55  52  93   2  59  45  68]
 [ 97  51  10  99  23  94  61  78  34  83]
 [ 40  83  10   1  78  41  44  34  12  26]
 [ 79  29  61  47  86  12  41  13  62  64]
 [ 75  78  71  73  61  61  92  96  84  77]
 [ 57  82  87  56  90  68  55  23   9  72]
 [ 65  94  10  89  14  69  25  21  65  31]
 [100  87  92  96  84  27  21  43  47  85]
 [ 69  42  17  19   7  51  50  23  80  68]
 [ 64  45  61  92  27  24  97  39  16  56]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[34.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 51.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 47.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 61.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 6

In [ ]:
import torch
# 创建张量 A：形状 (3, 4)，元素为 [0, 11] 的整数
A = torch.arange(12).reshape(3, 4)
# 创建张量 B：形状 (3, 4)，服从标准正态分布
B = _____
# 判断以下操作是否正确：
# (1) A.shape 返回 torch.Size([3, 4])
# (2) B.dtype 默认返回 torch.float32
# (3) A.device 默认为 GPU

In [ ]:
import torch
# 创建张量 A：形状 (3, 4)，元素为 [0, 11] 的整数
A = torch.arange(12).reshape(3, 4)
# 创建张量 B：形状 (3, 4)，服从标准正态分布
B = torch.randn(3,4)
# 判断以下操作是否正确：
# (1) A.shape 返回 torch.Size([3, 4])  √
# (2) B.dtype 默认返回 torch.float32  √
# (3) A.device 默认为 GPU   ×默认为CPU

In [7]:
import torch 
a = torch.tensor([[1], [2], [3]])  # shape (3, 1)
b = torch.tensor([4, 5, 6])        # shape (3,)
# 计算 c = a + b，并写出 c 的形状
c = ([[5, 6, 7],
    [6, 7, 8],
    [7, 8, 9]])
C = a+b
print(C.size())
# 计算 d = a * b，并解释广播规则
d = ([[ 4,  5,  6],
    [ 8, 10, 12],
    [12, 15, 18]])


torch.Size([3, 3])


广播规则：从最右边维度开始对比，从高维到低维，两个数字都等于1，符合广播规则；只要有一个位置两个数字大于1且不相等，则不符合广播规则